// generated by tools/fw_assets.py — do not edit
#pragma once
namespace A {
constexpr int SPLASH = 0;
constexpr int BG = 1;
constexpr int SPIN = 2;
constexpr int HEART = 3;
constexpr int IC_FOOTSTEPS = 4;
constexpr int IC_FLAME = 5;
constexpr int IC_BLUETOOTH = 6;
constexpr int IC_BATTERY = 7;
constexpr int IC_STOPWATCH = 8;
constexpr int IC_MOON = 9;
constexpr int IC_GAUGE = 10;
constexpr int IC_MAP_PIN = 11;
constexpr int IC_SMARTPHONE = 12;
constexpr int IC_SHIELD = 13;
constexpr int F_LABEL = 14;
constexpr int F_SMALL = 15;
constexpr int F_BODY = 16;
constexpr int F_TITLE = 17;
constexpr int F_BRAND = 18;
constexpr int F_BIG = 19;
constexpr int QR = 20;
constexpr int COUNT = 21;
}  // namespace A
